# Generated by Django 3.0.8 on 2020-10-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_Name_Label', models.PositiveSmallIntegerField()),
                ('State_Name', models.CharField(max_length=100)),
                ('District_Name_Label', models.PositiveSmallIntegerField()),
                ('District_Name', models.CharField(max_length=100)),
                ('Season_Label', models.PositiveSmallIntegerField(default=4)),
                ('Season', models.CharField(max_length=50)),
                ('Crop_Label', models.PositiveSmallIntegerField()),
                ('Crop', models.CharField(max_length=50)),
                ('Area', models.FloatField()),
                ('Production', models.FloatField()),
                ('ANNUAL_RAIN', models.FloatField()),
                ('KHARIF_RAIN', models.FloatField()),
                ('RABI_RAIN', models.FloatField()),
                ('SUMMER_RAIN', models.FloatField()),
                ('ANNUAL_GROUND_WATER', models.FloatField()),
                ('ANNUAL_GROUND_WATER_FOR_IRRIGATION', models.FloatField()),
            ],
        ),
    ]
