# Generated by Django 3.0.8 on 2020-10-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Crop', models.CharField(max_length=200)),
                ('fertilizer_url', models.CharField(max_length=200)),
                ('pesticide_url', models.CharField(max_length=200)),
                ('seeds_url', models.CharField(max_length=200)),
                ('method_url', models.CharField(max_length=200)),
            ],
        ),
    ]
